# MindCare Backend Deployment Configuration for Render.com
services:
  - type: web
    name: mindcare-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: "java -jar app.jar"
    healthCheckPath: "/api/public/health"
    port: 8080
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2h2jf75r7bs73fl9k1g-a.oregon-postgres.render.com/mindcare_iky2?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: mindcare_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: tECpz6lKn0b0hIqTWNsbTE1U26UoCQQh
      - key: JWT_SECRET_KEY
        value: MindCare_Connect_Super_Secret_Key_2025_Bangladesh_Mental_Health_Platform_Production_256_Bit_Key
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: ADMIN_EMAIL
        value: admin@mindcareconnect.bd
      - key: ADMIN_PASSWORD
        value: MindCare@AdminProd2025!
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://mind-care-zeta.vercel.app,https://mind-care-git-master-raiyanfzs845-3659s-projects.vercel.app"
      - key: PORT
        value: "8080"
      - key: APP_BASE_URL
        value: "https://mindcare-backend.render.com/api"
      - key: STORAGE_LOCAL_PATH
        value: "/tmp/uploads"
      - key: STORAGE_MAX_FILE_SIZE
        value: "10485760"

databases:
  - name: mindcare-database
    databaseName: mindcare
    user: mindcare_user
    plan: free